export const ALL_ROLE_REQUEST = "ALL_ROLE_REQUEST";
export const ALL_ROLE_SUCCESS = "ALL_ROLE_SUCCESS";
export const ALL_ROLE_FAIL = "ALL_ROLE_FAIL";

export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const CREATE_ROLE_RESET = "CREATE_ROLE_RESET";

export const UPDATE_ROLE_REQUEST = "UPDATE_ROLE_REQUEST";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_RESET = "UPDATE_ROLE_RESET";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const DELETE_ROLE_RESET = "DELETE_ROLE_RESET";

export const ALL_PERMISSION_REQUEST = "ALL_PERMISSION_REQUEST";
export const ALL_PERMISSION_SUCCESS = "ALL_PERMISSION_SUCCESS";
export const ALL_PERMISSION_FAIL = "ALL_PERMISSION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
