export const ALL_HOME_MENU_REQUEST = "ALL_HOME_MENU_REQUEST";
export const ALL_HOME_MENU_SUCCESS = "ALL_HOME_MENU_SUCCESS";
export const ALL_HOME_MENU_FAIL = "ALL_HOME_MENU_FAIL";

export const CREATE_HOME_MENU_REQUEST = "CREATE_HOME_MENU_REQUEST";
export const CREATE_HOME_MENU_SUCCESS = "CREATE_HOME_MENU_SUCCESS";
export const CREATE_HOME_MENU_FAIL = "CREATE_HOME_MENU_FAIL";
export const CREATE_HOME_MENU_RESET = "CREATE_HOME_MENU_RESET";

export const UPDATE_HOME_MENU_REQUEST = "UPDATE_HOME_MENU_REQUEST";
export const UPDATE_HOME_MENU_SUCCESS = "UPDATE_HOME_MENU_SUCCESS";
export const UPDATE_HOME_MENU_RESET = "UPDATE_HOME_MENU_RESET";
export const UPDATE_HOME_MENU_FAIL = "UPDATE_HOME_MENU_FAIL";

export const DELETE_HOME_MENU_REQUEST = "DELETE_HOME_MENU_REQUEST";
export const DELETE_HOME_MENU_SUCCESS = "DELETE_HOME_MENU_SUCCESS";
export const DELETE_HOME_MENU_FAIL = "DELETE_HOME_MENU_FAIL";
export const DELETE_HOME_MENU_RESET = "DELETE_HOME_MENU_RESET";

export const ALL_HOME_SLIDER_REQUEST = "ALL_HOME_SLIDER_REQUEST";
export const ALL_HOME_SLIDER_SUCCESS = "ALL_HOME_SLIDER_SUCCESS";
export const ALL_HOME_SLIDER_FAIL = "ALL_HOME_SLIDER_FAIL";

export const CREATE_HOME_SLIDER_REQUEST = "CREATE_HOME_SLIDER_REQUEST";
export const CREATE_HOME_SLIDER_SUCCESS = "CREATE_HOME_SLIDER_SUCCESS";
export const CREATE_HOME_SLIDER_FAIL = "CREATE_HOME_SLIDER_FAIL";
export const CREATE_HOME_SLIDER_RESET = "CREATE_HOME_SLIDER_RESET";

export const UPDATE_HOME_SLIDER_REQUEST = "UPDATE_HOME_SLIDER_REQUEST";
export const UPDATE_HOME_SLIDER_SUCCESS = "UPDATE_HOME_SLIDER_SUCCESS";
export const UPDATE_HOME_SLIDER_RESET = "UPDATE_HOME_SLIDER_RESET";
export const UPDATE_HOME_SLIDER_FAIL = "UPDATE_HOME_SLIDER_FAIL";

export const DELETE_HOME_SLIDER_REQUEST = "DELETE_HOME_SLIDER_REQUEST";
export const DELETE_HOME_SLIDER_SUCCESS = "DELETE_HOME_SLIDER_SUCCESS";
export const DELETE_HOME_SLIDER_FAIL = "DELETE_HOME_SLIDER_FAIL";
export const DELETE_HOME_SLIDER_RESET = "DELETE_HOME_SLIDER_RESET";

export const HOME_FOOTER_REQUEST = "HOME_FOOTER_REQUEST";
export const HOME_FOOTER_SUCCESS = "HOME_FOOTER_SUCCESS";
export const HOME_FOOTER_FAIL = "HOME_FOOTER_FAIL";

export const UPDATE_HOME_FOOTER_REQUEST = "UPDATE_HOME_FOOTER_REQUEST";
export const UPDATE_HOME_FOOTER_SUCCESS = "UPDATE_HOME_FOOTER_SUCCESS";
export const UPDATE_HOME_FOOTER_RESET = "UPDATE_HOME_FOOTER_RESET";
export const UPDATE_HOME_FOOTER_FAIL = "UPDATE_HOME_FOOTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
