export const ALL_HOME_MENU_REQUEST = "ALL_HOME_MENU_REQUEST";
export const ALL_HOME_MENU_SUCCESS = "ALL_HOME_MENU_SUCCESS";
export const ALL_HOME_MENU_FAIL = "ALL_HOME_MENU_FAIL";

export const CREATE_HOME_MENU_REQUEST = "CREATE_HOME_MENU_REQUEST";
export const CREATE_HOME_MENU_SUCCESS = "CREATE_HOME_MENU_SUCCESS";
export const CREATE_HOME_MENU_FAIL = "CREATE_HOME_MENU_FAIL";
export const CREATE_HOME_MENU_RESET = "CREATE_HOME_MENU_RESET";

export const UPDATE_HOME_MENU_REQUEST = "UPDATE_HOME_MENU_REQUEST";
export const UPDATE_HOME_MENU_SUCCESS = "UPDATE_HOME_MENU_SUCCESS";
export const UPDATE_HOME_MENU_RESET = "UPDATE_HOME_MENU_RESET";
export const UPDATE_HOME_MENU_FAIL = "UPDATE_HOME_MENU_FAIL";

export const DELETE_HOME_MENU_REQUEST = "DELETE_HOME_MENU_REQUEST";
export const DELETE_HOME_MENU_SUCCESS = "DELETE_HOME_MENU_SUCCESS";
export const DELETE_HOME_MENU_FAIL = "DELETE_HOME_MENU_FAIL";
export const DELETE_HOME_MENU_RESET = "DELETE_HOME_MENU_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
