export const ALL_WEBSITE_REQUEST = "ALL_WEBSITE_REQUEST";
export const ALL_WEBSITE_SUCCESS = "ALL_WEBSITE_SUCCESS";
export const ALL_WEBSITE_FAIL = "ALL_WEBSITE_FAIL";

export const CREATE_WEBSITE_REQUEST = "CREATE_WEBSITE_REQUEST";
export const CREATE_WEBSITE_SUCCESS = "CREATE_WEBSITE_SUCCESS";
export const CREATE_WEBSITE_FAIL = "CREATE_WEBSITE_FAIL";
export const CREATE_WEBSITE_RESET = "CREATE_WEBSITE_RESET";

export const UPDATE_WEBSITE_REQUEST = "UPDATE_WEBSITE_REQUEST";
export const UPDATE_WEBSITE_SUCCESS = "UPDATE_WEBSITE_SUCCESS";
export const UPDATE_WEBSITE_RESET = "UPDATE_WEBSITE_RESET";
export const UPDATE_WEBSITE_FAIL = "UPDATE_WEBSITE_FAIL";

export const DELETE_WEBSITE_REQUEST = "DELETE_WEBSITE_REQUEST";
export const DELETE_WEBSITE_SUCCESS = "DELETE_WEBSITE_SUCCESS";
export const DELETE_WEBSITE_FAIL = "DELETE_WEBSITE_FAIL";
export const DELETE_WEBSITE_RESET = "DELETE_WEBSITE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
